[platformio]
default_envs = waveshare_esp32_s3_touch_lcd_146
extra_configs = 

[env:waveshare_esp32_s3_touch_lcd_146]
platform = espressif32 @ 6.9.0
board = waveshare-esp32-s3-touch-lcd-146
framework = espidf
build_type = debug
board_build.sdkconfig = sdkconfig.defaults
board_build.partitions = partitions.csv
monitor_speed = 115200
monitor_filters = esp32_exception_decoder, time
upload_port = COM3
upload_protocol = custom
build_unflags = -Os
build_flags = -O0
extra_scripts = pre:scripts/add_waveshare_drivers.py, pre:scripts/upload_waveshare.py
