/* Regenerate the RGB565 run-length source using the reference LVGL renderer. */
#define CHRONVS_WATCH_RINGS_REFERENCE
#define main watch_render_test_main
#include "watch_render_test.c"
#undef main
#include "src/draw/sw/lv_draw_sw.h"

int main(int argc, char **argv) {
    assert(argc == 2);
    lv_init();
    static lv_color_t pixels[412];
    static lv_disp_draw_buf_t buffer;
    static lv_disp_drv_t driver;
    lv_disp_draw_buf_init(&buffer,pixels,NULL,412);
    lv_disp_drv_init(&driver);
    driver.hor_res=driver.ver_res=412;
    driver.draw_buf=&buffer; driver.flush_cb=flush;
    lv_disp_drv_register(&driver);
    lv_refr_now(NULL);
    lv_draw_sw_ctx_t sw;
    lv_draw_sw_init_ctx(&driver,&sw.base_draw);
    static uint16_t runs[8192][2], offsets[413];
    unsigned count=0;
    for (int y=0;y<412;++y) {
        lv_area_t area={0,y,411,y};
        sw.base_draw.buf=pixels;
        sw.base_draw.buf_area=&area;
        sw.base_draw.clip_area=&area;
        for (int x=0;x<412;++x) pixels[x]=lv_color_hex(COLOR_BEZEL_DARK);
        draw_case_rings(&sw.base_draw,205.5f,205.5f);
        offsets[y]=count;
        for (int x=0;x<412;) {
            uint16_t color=pixels[x].full;
            do { ++x; } while (x<412 && pixels[x].full==color);
            assert(count<8192);
            runs[count][0]=x; runs[count++][1]=color;
        }
    }
    offsets[412]=count;
    FILE *out=fopen(argv[1],"wb"); assert(out);
    fprintf(out,"/* Generated by tests/generate_watch_ring_cache.c with LVGL 8.3.11.\n"
                " * Fixed 412px case rings; RGB565 runs end at exclusive x. */\n"
                "#pragma once\n#include <stdint.h>\n\n"
                "static const uint16_t watch_ring_offsets[413] = {\n");
    for(unsigned i=0;i<413;++i) fprintf(out,"%u,%s",offsets[i],i==412?"":i%16==15?"\n":" ");
    fprintf(out,"\n};\nstatic const uint16_t watch_ring_runs[%u][2] = {\n",count);
    for(unsigned i=0;i<count;++i) fprintf(out,"{%u,0x%04x},%s",runs[i][0],runs[i][1],i+1==count?"":i%6==5?"\n":" ");
    fprintf(out,"\n};\n"); assert(fclose(out)==0);
    printf("Ring cache: %u runs, %u bytes of const data; scratch line 824 bytes.\n",
           count,(unsigned)(count*4+sizeof(offsets)));
    return 0;
}
