/* Generate only pixels replaced by the stationary mother face, after rings. */
#define main watch_render_test_main
#include "watch_render_test.c"
#undef main

int main(int argc, char **argv) {
    assert(argc == 2);
    lv_init();
    static lv_color_t pixels[412], before[412];
    static lv_disp_draw_buf_t buffer;
    static lv_disp_drv_t driver;
    lv_disp_draw_buf_init(&buffer, pixels, NULL, 412);
    lv_disp_drv_init(&driver);
    driver.hor_res = driver.ver_res = 412;
    driver.draw_buf = &buffer; driver.flush_cb = flush;
    lv_disp_drv_register(&driver);
    lv_refr_now(NULL);
    lv_draw_sw_ctx_t sw;
    lv_draw_sw_init_ctx(&driver, &sw.base_draw);
    static uint16_t runs[8192][2], offsets[413], starts[412];
    unsigned count = 0;
    for (int y = 0; y < 412; ++y) {
        lv_area_t area = {0, y, 411, y};
        sw.base_draw.buf = pixels; sw.base_draw.buf_area = &area;
        sw.base_draw.clip_area = &area;
        for (int x = 0; x < 412; ++x) pixels[x] = lv_color_hex(COLOR_BEZEL_DARK);
        draw_case_rings(&sw.base_draw, 205.5f, 205.5f);
        memcpy(before, pixels, sizeof(before));
        draw_circle(&sw.base_draw, 205.5f, 205.5f, 154, COLOR_FACE, COLOR_TRACK, 1);
        int first = 0, last = 411;
        while (first < 412 && pixels[first].full == before[first].full) ++first;
        while (last >= first && pixels[last].full == before[last].full) --last;
        offsets[y] = count; starts[y] = first;
        for (int x = first; x <= last;) {
            uint16_t color = pixels[x].full;
            do { ++x; } while (x <= last && pixels[x].full == color);
            assert(count < 8192);
            runs[count][0] = x; runs[count++][1] = color;
        }
    }
    offsets[412] = count;
    FILE *out = fopen(argv[1], "wb"); assert(out);
    fprintf(out, "/* Generated by tests/generate_watch_mother_cache.c; LVGL 8.3.11.\n"
                 " * Stationary mother face over case rings; changed spans only, RGB565. */\n"
                 "#pragma once\n#include <stdint.h>\n\n"
                 "static const uint16_t watch_mother_offsets[413] = {\n");
    for (unsigned i=0;i<413;++i) fprintf(out,"%u,%s",offsets[i],i==412?"":i%16==15?"\n":" ");
    fprintf(out,"\n};\nstatic const uint16_t watch_mother_starts[412] = {\n");
    for (unsigned i=0;i<412;++i) fprintf(out,"%u,%s",starts[i],i==411?"":i%16==15?"\n":" ");
    fprintf(out,"\n};\nstatic const uint16_t watch_mother_runs[%u][2] = {\n",count);
    for (unsigned i=0;i<count;++i) fprintf(out,"{%u,0x%04x},%s",runs[i][0],runs[i][1],i+1==count?"":i%6==5?"\n":" ");
    fprintf(out,"\n};\n"); assert(fclose(out)==0);
    printf("Mother cache: %u runs, %u bytes; reuses ring scratch.\n", count,
           (unsigned)(count*4+sizeof(offsets)+sizeof(starts)));
    return 0;
}
