"""Convert the approved weather PNGs to LVGL RGB565A8 C images.

Requires ffmpeg on PATH. RGB565 bytes follow LV_COLOR_16_SWAP=1.
"""

from pathlib import Path
import subprocess


ROOT = Path(__file__).resolve().parents[1]
ART = ROOT / "assets" / "weather"
OUT = ROOT / "src" / "ui" / "weather_art.c"
NAMES = ("sun", "partly_cloudy", "cloud", "fog", "rain", "snow", "storm")
SIZES = (44, 88)


def pixels(path: Path, size: int) -> bytes:
    result = subprocess.run(
        ["ffmpeg", "-v", "error", "-i", str(path), "-vf",
         f"scale={size}:{size}:flags=lanczos,format=rgba", "-f", "rawvideo",
         "-pix_fmt", "rgba", "-"], check=True, stdout=subprocess.PIPE
    )
    if len(result.stdout) != size * size * 4:
        raise ValueError(f"Unexpected image size: {path}")
    return result.stdout


def lvgl_bytes(rgba: bytes) -> bytes:
    colors = bytearray()
    alpha = bytearray()
    for i in range(0, len(rgba), 4):
        r, g, b, a = rgba[i:i + 4]
        # LVGL's swapped 16-bit color: green high + red, blue + green low.
        colors.extend((((g >> 5) & 7) | (r & 0xF8),
                       (b >> 3) | ((g & 0x1C) << 3)))
        alpha.append(a)
    return colors + alpha


def main() -> None:
    lines = [
        '#include "ui/weather_art.h"',
        '',
        '/* Generated by scripts/generate_weather_art.py from the assets/weather PNG files. */',
    ]
    for name in NAMES:
        path = ART / f"{name}.png"
        for size in SIZES:
            data = lvgl_bytes(pixels(path, size))
            symbol = f"weather_{name}_{size}"
            lines.append(f"static const uint8_t {symbol}_data[] = {{")
            for start in range(0, len(data), 24):
                lines.append("    " + ", ".join(f"0x{x:02x}" for x in data[start:start + 24]) + ",")
            lines.extend((
                '};',
                f'static const lv_img_dsc_t {symbol} = {{',
                f'    .header.cf = LV_IMG_CF_RGB565A8, .header.w = {size}, .header.h = {size},',
                f'    .data_size = sizeof({symbol}_data), .data = {symbol}_data,',
                '};',
            ))
    for size in SIZES:
        lines.append(f"const lv_img_dsc_t *chronvs_weather_art_{size}(chronvs_weather_icon_t icon) {{")
        lines.append("    switch (icon) {")
        for name in NAMES:
            lines.append(f"    case WEATHER_{name.upper()}: return &weather_{name}_{size};")
        lines.extend(("    default: return &weather_cloud_%d;" % size, "    }", "}"))
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
