"""Split the approved Clima face into flash-resident LVGL image layers.

The base was created from the user's reference with its relief removed. The
four relief layers retain pixels from the approved composite, with feathered
edges so each can be positioned or replaced independently. Requires ffmpeg.
"""

from pathlib import Path
from math import hypot
import subprocess


ROOT = Path(__file__).resolve().parents[1]
ART = ROOT / "assets" / "weather"
OUTPUT = ROOT / "src" / "ui" / "weather_face.c"
SIZE = 412
LAYERS = (
    ("socket", 234, 54, 123, 123),
    ("divider", 74, 241, 265, 21),
    ("left_panel", 25, 253, 185, 159),
    ("right_panel", 203, 253, 185, 159),
)


def read_rgba(path: Path) -> bytes:
    result = subprocess.run(
        ["ffmpeg", "-v", "error", "-i", str(path), "-f", "rawvideo",
         "-pix_fmt", "rgba", "-"], check=True, stdout=subprocess.PIPE
    )
    if len(result.stdout) != SIZE * SIZE * 4:
        raise ValueError(f"Expected 412 x 412 image: {path}")
    return result.stdout


def write_png(path: Path, rgba: bytes, width: int, height: int) -> None:
    subprocess.run(
        ["ffmpeg", "-v", "error", "-y", "-f", "rawvideo", "-pix_fmt", "rgba",
         "-s", f"{width}x{height}", "-i", "-", "-frames:v", "1", str(path)],
        input=rgba, check=True
    )


def opacity(name: str, x: int, y: int, left: int, top: int,
            width: int, height: int) -> int:
    radial = max(0.0, min(1.0, (198.5 - hypot(x - 205.5, y - 205.5)) / 3.0))
    if name == "socket":
        radius = hypot(x - 295, y - 115)
        shape = max(0, min(255, round((60 - radius) * 255 / 8)))
        return round(shape * radial)
    feather = 5 if name == "divider" else 10
    distance = min(x - left, left + width - 1 - x, y - top,
                   top + height - 1 - y)
    shape = max(0, min(255, round(distance * 255 / feather)))
    return round(shape * radial)


def cut_layer(source: bytes, name: str, left: int, top: int,
              width: int, height: int) -> bytes:
    out = bytearray()
    for y in range(top, top + height):
        for x in range(left, left + width):
            i = 4 * (y * SIZE + x)
            out.extend(source[i:i + 3])
            out.append(opacity(name, x, y, left, top, width, height))
    return bytes(out)


def lvgl_bytes(rgba: bytes, alpha: bool) -> bytes:
    colors = bytearray()
    alphas = bytearray()
    for i in range(0, len(rgba), 4):
        r, g, b, a = rgba[i:i + 4]
        # LV_COLOR_16_SWAP=1: green high/red, then blue/green low.
        colors.extend((((g >> 5) & 7) | (r & 0xF8),
                       (b >> 3) | ((g & 0x1C) << 3)))
        if alpha:
            alphas.append(a)
    return colors + alphas


def emit_image(lines: list[str], name: str, rgba: bytes,
               width: int, height: int, alpha: bool) -> None:
    data = lvgl_bytes(rgba, alpha)
    lines.append(f"static const uint8_t {name}_data[] = {{")
    for start in range(0, len(data), 24):
        lines.append("    " + ", ".join(f"0x{x:02x}" for x in data[start:start + 24]) + ",")
    lines.extend((
        '};',
        f'static const lv_img_dsc_t {name} = {{',
        f'    .header.cf = LV_IMG_CF_{"RGB565A8" if alpha else "TRUE_COLOR"},',
        f'    .header.w = {width}, .header.h = {height},',
        f'    .data_size = sizeof({name}_data), .data = {name}_data,',
        '};',
    ))


def main() -> None:
    original = read_rgba(ART / "weather_face.png")
    base = read_rgba(ART / "weather_face_base.png")
    lines = ['#include "ui/weather_face.h"', '',
             '/* Generated by scripts/generate_weather_face.py. */']
    emit_image(lines, "face_base", base, SIZE, SIZE, False)
    for name, x, y, width, height in LAYERS:
        crop = cut_layer(original, name, x, y, width, height)
        write_png(ART / f"weather_{name}.png", crop, width, height)
        emit_image(lines, f"face_{name}", crop, width, height, True)
    lines.append('const chronvs_weather_face_layer_t chronvs_weather_face_layers[5] = {')
    lines.append('    {&face_base, 0, 0},')
    for name, x, y, _, _ in LAYERS:
        lines.append(f'    {{&face_{name}, {x}, {y}}},')
    lines.append('};')
    OUTPUT.write_text("\n".join(lines) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
