"""Print the LVGL Portuguese supplement (Pillow, bundled Montserrat-Medium)."""
from pathlib import Path
from PIL import ImageFont

root = Path(__file__).resolve().parents[1]
font = ImageFont.truetype(str(root / '.vendor-reference/example/ESP-IDF-5.3.2/ESP32-S3-Touch-LCD-1.46-Test/components/lvgl__lvgl/scripts/built_in_font/Montserrat-Medium.ttf'), 18)
chars = sorted(set('áàãâçéêíóôõúÁÀÃÂÇÉÊÍÓÔÕÚ'))
bitmap, entries = [], []
for char in chars:
    mask, (left, top) = font.getmask2(char, mode='L', anchor='ls')
    w, h = mask.size
    entries.append(f'    {{{ord(char)}, {len(bitmap)}, {round(font.getlength(char))}, {w}, {h}, {left}, {-top-h}}},')
    bitmap.extend(mask)
print('/* Generated by scripts/generate_mnemo_font.py; Montserrat, SIL OFL (vendor reference). */')
print('#include "ui/mnemo_font.h"\n')
print('static const uint8_t bitmap[] = {')
for i in range(0, len(bitmap), 24):
    print('    ' + ','.join(str(v) for v in bitmap[i:i+24]) + ',')
print('};\nstatic const struct { uint16_t code, offset, advance, w, h; int16_t x, y; } glyphs[] = {')
print('\n'.join(entries))
print('''};
static bool describe(const lv_font_t *font, lv_font_glyph_dsc_t *out, uint32_t code, uint32_t next) {
    (void)font; (void)next;
    for (unsigned i = 0; i < sizeof(glyphs)/sizeof(glyphs[0]); ++i) {
        if (glyphs[i].code != code) continue;
        *out = (lv_font_glyph_dsc_t){ .adv_w = glyphs[i].advance, .box_w = glyphs[i].w,
            .box_h = glyphs[i].h, .ofs_x = glyphs[i].x, .ofs_y = glyphs[i].y, .bpp = 8 };
        return true;
    }
    return false;
}
static const uint8_t *get_bitmap(const lv_font_t *font, uint32_t code) {
    (void)font;
    for (unsigned i = 0; i < sizeof(glyphs)/sizeof(glyphs[0]); ++i)
        if (glyphs[i].code == code) return bitmap + glyphs[i].offset;
    return NULL;
}
const lv_font_t chronvs_mnemo_font = {
    .get_glyph_dsc = describe, .get_glyph_bitmap = get_bitmap,
    .line_height = 24, .base_line = 5, .fallback = &lv_font_montserrat_18
};''')
